### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

spring:
  h2:
    console:
      enabled: true
      path: /h2

spring.jpa:
    hibernate.ddl-auto: update

logging:
  org.hibernate: INFO
  level.org.springframework.web: DEBUG



server:
  port: 8090

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false

#default project info followed by actual injected pom-specified values.
project:
  name: ${project.name}
  version: 0.1
  description: kotlin rest api
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
